import { Command } from "commander";
import * as fs from "node:fs";
import * as path from "node:path";

/** Minimal project.godot content for a new GodotForge project. */
function projectGodotContent(projectName: string): string {
  return `; Engine configuration file.
; Generated by GodotForge CLI.

config_version=5

[application]

config/name="${projectName}"
config/features=PackedStringArray("4.4")

[editor_plugins]

enabled=PackedStringArray("res://addons/godot_forge/plugin.cfg")
`;
}

/** Minimal plugin.cfg for the GodotForge editor plugin. */
function pluginCfgContent(): string {
  return `[plugin]
name="GodotForge"
description="AI-powered game creation platform"
author="GodotForge"
version="0.1.0"
script="plugin.gd"
`;
}

/** Minimal plugin.gd stub so Godot can load the plugin entry point. */
function pluginGdContent(): string {
  return `@tool
extends EditorPlugin

func _enter_tree() -> void:
\tprint("GodotForge plugin activated")

func _exit_tree() -> void:
\tprint("GodotForge plugin deactivated")
`;
}

/** Default .gdignore content for build artifacts. */
function gdignoreContent(): string {
  return `# GodotForge build artifacts
.godot/
`;
}

/**
 * Directories that every GodotForge project should contain.
 * The key is the relative path; the value is an optional README placeholder.
 */
const PROJECT_DIRS: Record<string, string | null> = {
  "scenes": "Place your .tscn scene files here.",
  "scripts": "Place your GDScript (.gd) files here.",
  "assets/sprites": "Sprite and 2-D image assets.",
  "assets/models": "3-D model assets (.glb, .gltf).",
  "assets/audio": "Sound effects and music.",
  "assets/fonts": "Font resources.",
  "assets/ui": "UI theme and texture assets.",
  "addons/godot_forge": null, // populated by plugin copy
};

/** Resolve the source plugin directory shipped alongside the monorepo. */
function resolvePluginSource(): string | null {
  // Walk up from the CLI package to find the monorepo godot-plugin package.
  // Expected layout: <root>/packages/cli  and  <root>/packages/godot-plugin
  const cliDir = path.resolve(
    new URL(import.meta.url).pathname,
    "..",
    "..",
    "..",
  );
  const candidate = path.join(
    cliDir,
    "..",
    "godot-plugin",
    "addons",
    "godot_forge",
  );
  if (fs.existsSync(candidate)) {
    return candidate;
  }
  return null;
}

/** Recursively copy a directory tree, creating destination dirs as needed. */
function copyDirSync(src: string, dest: string): void {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

export function registerInitCommand(program: Command): void {
  program
    .command("init")
    .description("Initialize a new GodotForge project")
    .argument("[directory]", "Target directory (defaults to current directory)", ".")
    .option("-n, --name <name>", "Project name")
    .option("--no-plugin", "Skip copying the GodotForge editor plugin")
    .action((directory: string, options: { name?: string; plugin: boolean }) => {
      const targetDir = path.resolve(directory);
      const projectName =
        options.name ?? (path.basename(targetDir) || "GodotForgeProject");

      console.log(`Initializing GodotForge project "${projectName}" in ${targetDir}`);

      // Create root directory if needed.
      fs.mkdirSync(targetDir, { recursive: true });

      // Create sub-directories and optional placeholders.
      for (const [relDir, readme] of Object.entries(PROJECT_DIRS)) {
        const dirPath = path.join(targetDir, relDir);
        fs.mkdirSync(dirPath, { recursive: true });
        if (readme) {
          const readmePath = path.join(dirPath, ".gdkeep");
          if (!fs.existsSync(readmePath)) {
            fs.writeFileSync(readmePath, `# ${readme}\n`);
          }
        }
      }

      // Write project.godot
      const godotPath = path.join(targetDir, "project.godot");
      if (fs.existsSync(godotPath)) {
        console.log("  project.godot already exists — skipping");
      } else {
        fs.writeFileSync(godotPath, projectGodotContent(projectName));
        console.log("  Created project.godot");
      }

      // Write .gdignore
      const gdignorePath = path.join(targetDir, ".gdignore");
      if (!fs.existsSync(gdignorePath)) {
        fs.writeFileSync(gdignorePath, gdignoreContent());
        console.log("  Created .gdignore");
      }

      // Copy or scaffold the GodotForge plugin.
      if (options.plugin) {
        const pluginDest = path.join(targetDir, "addons", "godot_forge");
        const pluginSrc = resolvePluginSource();
        if (pluginSrc) {
          console.log("  Copying GodotForge plugin from monorepo...");
          copyDirSync(pluginSrc, pluginDest);
          console.log("  Plugin copied successfully");
        } else {
          // Scaffold minimal plugin files so the project is still valid.
          console.log("  Plugin source not found — scaffolding minimal plugin");
          fs.mkdirSync(pluginDest, { recursive: true });

          const cfgPath = path.join(pluginDest, "plugin.cfg");
          if (!fs.existsSync(cfgPath)) {
            fs.writeFileSync(cfgPath, pluginCfgContent());
          }

          const gdPath = path.join(pluginDest, "plugin.gd");
          if (!fs.existsSync(gdPath)) {
            fs.writeFileSync(gdPath, pluginGdContent());
          }
        }
      }

      console.log("");
      console.log("Project initialized successfully!");
      console.log("Next steps:");
      console.log(`  cd ${path.relative(process.cwd(), targetDir) || "."}`);
      console.log("  godot-forge serve        # Start AI + MCP services");
      console.log("  godot-forge generate     # Generate content via AI");
    });
}
