import { GodotConnection } from "../transport/websocket.js";
import { RegisteredTool } from "./index.js";

export function registerAnimationTools(godot: GodotConnection): RegisteredTool[] {
  return [
    { definition: { name: "create_animation_player", description: "创建 AnimationPlayer 节点", inputSchema: { type: "object", properties: { parent_path: { type: "string" }, node_name: { type: "string" } }, required: ["parent_path"] } }, handler: async (args) => godot.send("create_animation_player", args) },
    { definition: { name: "add_animation", description: "添加动画到 AnimationPlayer", inputSchema: { type: "object", properties: { player_path: { type: "string" }, animation_name: { type: "string" }, length: { type: "number" }, loop: { type: "boolean" } }, required: ["player_path", "animation_name"] } }, handler: async (args) => godot.send("add_animation", args) },
    { definition: { name: "add_animation_track", description: "为动画添加轨道", inputSchema: { type: "object", properties: { player_path: { type: "string" }, animation_name: { type: "string" }, track_type: { type: "string", description: "value | method | bezier | audio" }, node_path: { type: "string" }, property: { type: "string" } }, required: ["player_path", "animation_name", "track_type", "node_path"] } }, handler: async (args) => godot.send("add_animation_track", args) },
    { definition: { name: "set_keyframe", description: "设置动画关键帧", inputSchema: { type: "object", properties: { player_path: { type: "string" }, animation_name: { type: "string" }, track_index: { type: "number" }, time: { type: "number" }, value: { description: "关键帧值" } }, required: ["player_path", "animation_name", "track_index", "time", "value"] } }, handler: async (args) => godot.send("set_keyframe", args) },
    { definition: { name: "create_animation_tree", description: "创建 AnimationTree 节点", inputSchema: { type: "object", properties: { parent_path: { type: "string" }, player_path: { type: "string" }, tree_root_type: { type: "string", description: "state_machine | blend_tree | blend_space_1d | blend_space_2d" } }, required: ["parent_path", "player_path"] } }, handler: async (args) => godot.send("create_animation_tree", args) },
    { definition: { name: "set_blend_parameter", description: "设置动画树混合参数", inputSchema: { type: "object", properties: { tree_path: { type: "string" }, parameter: { type: "string" }, value: { type: "number" } }, required: ["tree_path", "parameter", "value"] } }, handler: async (args) => godot.send("set_blend_parameter", args) },
    { definition: { name: "play_animation", description: "播放动画", inputSchema: { type: "object", properties: { player_path: { type: "string" }, animation_name: { type: "string" }, speed: { type: "number" } }, required: ["player_path", "animation_name"] } }, handler: async (args) => godot.send("play_animation", args) },
    { definition: { name: "stop_animation", description: "停止动画", inputSchema: { type: "object", properties: { player_path: { type: "string" } }, required: ["player_path"] } }, handler: async (args) => godot.send("stop_animation", args) },
    { definition: { name: "create_tween", description: "创建 Tween 动画", inputSchema: { type: "object", properties: { node_path: { type: "string" }, property: { type: "string" }, from_value: { description: "起始值" }, to_value: { description: "目标值" }, duration: { type: "number" }, trans_type: { type: "string" }, ease_type: { type: "string" } }, required: ["node_path", "property", "to_value", "duration"] } }, handler: async (args) => godot.send("create_tween", args) },
    { definition: { name: "configure_tween", description: "配置 Tween 参数", inputSchema: { type: "object", properties: { node_path: { type: "string" }, loops: { type: "number" }, parallel: { type: "boolean" }, speed_scale: { type: "number" } }, required: ["node_path"] } }, handler: async (args) => godot.send("configure_tween", args) },
  ];
}
