import { GodotConnection } from "../transport/websocket.js";
import { RegisteredTool } from "./index.js";

export function registerUITools(godot: GodotConnection): RegisteredTool[] {
  return [
    { definition: { name: "create_ui_element", description: "创建 UI 控件", inputSchema: { type: "object", properties: { parent_path: { type: "string" }, element_type: { type: "string", description: "Button | Label | TextEdit | LineEdit | ProgressBar | etc." }, node_name: { type: "string" }, text: { type: "string" } }, required: ["parent_path", "element_type", "node_name"] } }, handler: async (args) => godot.send("create_ui_element", args) },
    { definition: { name: "set_theme", description: "设置节点主题", inputSchema: { type: "object", properties: { node_path: { type: "string" }, theme_path: { type: "string" } }, required: ["node_path", "theme_path"] } }, handler: async (args) => godot.send("set_theme", args) },
    { definition: { name: "set_style_override", description: "设置控件样式覆盖", inputSchema: { type: "object", properties: { node_path: { type: "string" }, style_type: { type: "string" }, properties: { type: "object" } }, required: ["node_path", "style_type"] } }, handler: async (args) => godot.send("set_style_override", args) },
    { definition: { name: "create_button", description: "创建按钮", inputSchema: { type: "object", properties: { parent_path: { type: "string" }, text: { type: "string" }, node_name: { type: "string" }, icon_path: { type: "string" } }, required: ["parent_path", "text"] } }, handler: async (args) => godot.send("create_button", args) },
    { definition: { name: "create_label", description: "创建文本标签", inputSchema: { type: "object", properties: { parent_path: { type: "string" }, text: { type: "string" }, node_name: { type: "string" }, font_size: { type: "number" } }, required: ["parent_path", "text"] } }, handler: async (args) => godot.send("create_label", args) },
    { definition: { name: "create_container", description: "创建容器节点", inputSchema: { type: "object", properties: { parent_path: { type: "string" }, container_type: { type: "string", description: "HBox | VBox | Grid | Margin | Center | Panel" }, node_name: { type: "string" } }, required: ["parent_path", "container_type"] } }, handler: async (args) => godot.send("create_container", args) },
    { definition: { name: "set_anchor_preset", description: "设置控件锚点预设", inputSchema: { type: "object", properties: { node_path: { type: "string" }, preset: { type: "string", description: "top_left | top_right | bottom_left | bottom_right | center | full_rect | etc." } }, required: ["node_path", "preset"] } }, handler: async (args) => godot.send("set_anchor_preset", args) },
    { definition: { name: "set_margin", description: "设置控件边距", inputSchema: { type: "object", properties: { node_path: { type: "string" }, left: { type: "number" }, top: { type: "number" }, right: { type: "number" }, bottom: { type: "number" } }, required: ["node_path"] } }, handler: async (args) => godot.send("set_margin", args) },
    { definition: { name: "set_size_flags", description: "设置控件大小标志", inputSchema: { type: "object", properties: { node_path: { type: "string" }, horizontal: { type: "number" }, vertical: { type: "number" } }, required: ["node_path"] } }, handler: async (args) => godot.send("set_size_flags", args) },
    { definition: { name: "create_ui_layout", description: "创建完整 UI 布局", inputSchema: { type: "object", properties: { parent_path: { type: "string" }, layout_type: { type: "string", description: "hud | menu | dialog | inventory" }, config: { type: "object" } }, required: ["parent_path", "layout_type"] } }, handler: async (args) => godot.send("create_ui_layout", args) },
  ];
}
